### ISSUE TITLE
paths too long on Windows?

### ISSUE THREAD

**Issue by pjmagee** [SlavaVedernikov/C4InterFlow#107]
I had to do this, not sure if you are aware

`git config --global core.longpaths true`

**Comment by SlavaVedernikov** [comment]
Thanks @pjmagee 

Yes, I am aware and I had to do the same :)

Not sure what can be done about this though...

Paths are long due to the nested nature of auto-generated Architecture as Code (e.g. in https://github.com/SlavaVedernikov/C4InterFlow/tree/master/Samples/dotnet.eShop/DotNetEShop/SoftwareSystems) as well as auto-generated Diagrams directory structure.

We may need to document `git config --global core.longpaths true` workaround in the wiki.

Would that be sufficient?

**Comment by pjmagee** [comment]
I think so yes, that should be good enough
